######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 14 21:36:57 2008
######################################################################

TEMPLATE = app
TARGET = Client
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += AccountForm.ui MainForm.ui

HEADERS += MainForm.h AccountForm.h
SOURCES += main.cpp MainForm.cpp AccountForm.cpp
QT += network
