######################################################################
# Automatically generated by qmake (2.01a) ?? ????. 15 14:28:57 2008
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += database.h sqlite3.h
SOURCES += database.cpp
LIBS += -L. -lsqlite3